# random_transforms = ["LinearTransform", 
#                      "AffineTransform", 
#                      "AffineTransform",
#                      "MoebiusTransform", 
#                      "MoebiusTransform",
#                      "InverseJuliaTransform", 
#                      "InverseJuliaTransform"]

random_transforms = [
                     "AffineTransform", 
                     "MoebiusTransform", 
                     "InverseJuliaTransform",
                     "InverseJuliaTransform"]



[image_settings]
width = 1000
height = 1000
path = "test.png"

[evaluation_settings]
num_iterations = 10000
num_points = 1000